const messages = {
  zh: {
    settings: '设置', backToBall: '回到小球身边', general: '常规', actions: '罗盘选项', about: '关于',
    generalLead: '和人家一起，把罗盘的模样、习性与醒来的方式，都慢慢调成你喜欢的样子吧♪', theme: '主题', peach: '桃粉', custom: '自定义', accent: '主题色', dark: '深色模式', language: '语言',
    appearance: '模样与大小', ballStyle: '悬浮球样式', solid: '单色球体', textBall: '文字球体', iconBall: '图标球体', ballText: '球体文字', ballTextPlaceholder: '最多四个字呀', image: '自定义图片', ballColor: '悬浮球颜色', chooseBallImage: '换一张图片', cropBallImage: '把这张图片裁成喜欢的样子', cropZoom: '缩放', ballRadius: '悬浮窗圆角', ballSize: '悬浮球大小', ballOpacity: '悬浮球透明度', compassOpacity: '窗口背景透明度', compassSize: '罗盘窗口大小', uiScale: '页面整体缩放', iconSize: '图标大小', fontSize: '文字大小', fontFamily: '字体',
    behavior: '小习惯', autoHide: '安静时，悄悄收起自己', autoHideSeconds: '等待时长', seconds: '秒', startup: '醒来的时候', scheduled: '登录时醒来（高优先级计划任务）', registry: '普通用户启动项',
    tabCompass: '长按 Tab 呼出罗盘', tabCompassHold: '按住时长', tabCompassHijack: '接管 Tab 键', tabCompassHijackHint: '按下 Tab 时先不急着送出去——等你松开，人家才原样转交一次；系统级 Alt+Tab / Win+Tab 不受影响。按满设定时长，罗盘仍会照常展开♪', tabCompassHint: '在任意界面按住 Tab，罗盘就会在屏幕中央轻轻展开；以中心为原点，朝哪个方向移动鼠标，就选那个方向的伙伴——松开就出发，回到中心松开，就当什么都没发生♪', moveToSelect: '朝想去的方向移动鼠标', releaseToLaunch: '松开 Tab 出发 · 回到中心取消', dialCenter: '罗盘',
    dropTitle: '把文件、文件夹或快捷方式，轻轻放进这里', releaseToAdd: '松开手，人家就收下♪', dropHint: '也可以轻点这里挑选；系统图标是默认的，想换成 Fluent 图标也可以呀', addAction: '添加空位', addSubmenu: '创建子菜单', administrator: '管理员', chooseIcon: '选择图标', customIcon: '选择自定义图片', useSystemIcon: '恢复系统图标', clear: '清空', target: '路径 / URI / URL / PowerShell 脚本', operation: '操作', chooseFile: '选择文件', label: '显示文字', type: '类型', dragReorderHint: '按住一个选项，就能把它挪到心里想去的位置♪', previewTitle: '此刻的模样', previewHint: '每改一笔，这里都会立刻亮起来；点子菜单进去看看，点中央按钮回到上一层♪', editorHint: '轻点瓦片就能选中编辑；按住瓦片拖到别的格位，它会和那里的伙伴交换位置♪', inspectorEmpty: '这里还空着呢……选一个瓦片，或把喜欢的东西拖进来吧♪', delete: '删除',
    iconLibrary: 'Fluent 图标库', searchIcon: '搜索图标', cancel: '取消', confirm: '确认', close: '关闭', apply: '确认应用', enterSubmenu: '进入子菜单', submenuType: '子菜单', appType: '应用程序 / CMD 命令', folderType: '文件夹', fileType: '文件', urlType: 'URL 链接', menuFull: '一层罗盘最多放得下 8 个选项，再多就要溢出来了♪', imageTooLarge: '这张图片有点沉……12 MB 以内人家才抱得动呀',
    aboutLead: '一个安安静静陪在桌面上的 Fluent 快捷启动器，Windows 10/11 与触屏都适用♪', version: '版本', author: '作者', contributors: '一起写故事的人', copyright: '版权', license: '开源协议', openRepository: '打开 GitHub 仓库', softwareUpdate: '软件更新', updateLead: '想看看罗盘有没有焕然一新？人家替你去星海那头问问♪', checkUpdate: '检查更新', checkingUpdate: '正在向星海询问……', latestVersion: '已经是最新的啦，今天也闪闪发亮呢♪', updateAvailable: '远方有新故事在等你', newVersion: '新的故事版本', releaseNotes: '发布说明', downloadInstall: '下载并安装', installingUpdate: '正在把新故事接回家……', downloadProgress: '下载进度', updateFailed: '这次没能接住……更新失败了', missingInstaller: '这个版本里没有找到 Windows x64 安装包呢', quit: '退出程序', quit1: '要和罗盘道别了吗？', quit2: '真的舍得让人家先回到记忆里吗……？', quit3: '最后一次确认：道别之后，小球和托盘都会睡去；想再见面，就要重新唤醒人家哦。', continueQuit: '那就道别吧', stay: '再陪一会儿', executed: '已经出发啦♪', startupUpdated: '醒来的方式，人家已经记下啦♪', inspectFailed: '这个小家伙……人家一时没看懂它', emptyAction: '新的选项', newMenu: '新的子菜单'
  },
  en: {
    settings: 'Settings', backToBall: 'Back to floating ball', general: 'General', actions: 'Compass items', about: 'About',
    generalLead: 'Control appearance, sizing, behavior, and startup.', theme: 'Theme', peach: 'Peach pink', custom: 'Custom', accent: 'Accent color', dark: 'Dark mode', language: 'Language',
    appearance: 'Size and display', ballStyle: 'Floating ball style', solid: 'Solid ball', textBall: 'Text ball', iconBall: 'Icon ball', ballText: 'Ball text', ballTextPlaceholder: 'Up to 4 characters', image: 'Custom image', ballColor: 'Ball color', chooseBallImage: 'Replace and crop image', cropBallImage: 'Crop floating image', cropZoom: 'Zoom', ballRadius: 'Floating window radius', ballSize: 'Ball size', ballOpacity: 'Ball opacity', compassOpacity: 'Window background opacity', compassSize: 'Compass window size', uiScale: 'UI scale', iconSize: 'Icon size', fontSize: 'Text size', fontFamily: 'Font',
    behavior: 'Behavior', autoHide: 'Auto-collapse when idle', autoHideSeconds: 'Idle timeout', seconds: 'sec', startup: 'Startup', scheduled: 'Start at login (high-priority task)', registry: 'Standard user startup entry',
    tabCompass: 'Hold Tab for compass', tabCompassHold: 'Hold duration', tabCompassHijack: 'Hijack the Tab key', tabCompassHijackHint: 'Tab presses are not sent to apps until you release the key, then exactly one press is delivered. System Alt+Tab / Win+Tab are unaffected, and holding past the duration still opens the compass.', tabCompassHint: 'Hold Tab anywhere to expand the compass at the screen center. The screen center is always the origin: move the mouse toward a direction to select that app, release Tab to launch it, or move back to the center and release to cancel.', moveToSelect: 'Move the mouse to choose a direction', releaseToLaunch: 'Release Tab to launch · Back to center to cancel', dialCenter: 'Compass',
    dropTitle: 'Drop files, folders, or shortcuts', releaseToAdd: 'Release to add', dropHint: 'Or click to browse. System icons are default; Fluent icons are optional overrides.', addAction: 'Add empty item', addSubmenu: 'Create submenu', administrator: 'Administrator', chooseIcon: 'Choose icon', customIcon: 'Choose custom image', useSystemIcon: 'Restore system icon', clear: 'Clear', target: 'Path / URI / URL / PowerShell script', operation: 'Operation', chooseFile: 'Browse', label: 'Display label', type: 'Type', dragReorderHint: 'Press and hold an item to drag and rearrange it.', previewTitle: 'Live preview', previewHint: 'The preview updates as you edit. Click a submenu to enter it, or the center button to go back.', editorHint: 'Click a tile to select and edit it; press and hold a tile to drag it to another slot to move or swap.', inspectorEmpty: 'Nothing here yet… pick a tile, or drop in something you like.', delete: 'Delete',
    iconLibrary: 'Fluent icon library', searchIcon: 'Search icons', cancel: 'Cancel', confirm: 'Confirm', close: 'Close', apply: 'Apply', enterSubmenu: 'Open submenu', submenuType: 'Submenu', appType: 'App / CMD command', folderType: 'Folder', fileType: 'File', urlType: 'URL link', menuFull: 'Each menu can contain up to 8 items.', imageTooLarge: 'Images must be 12 MB or smaller.',
    aboutLead: 'A Fluent quick launcher for Windows 10/11 and touch devices.', version: 'Version', author: 'Author', contributors: 'Contributors', copyright: 'Copyright', license: 'License', openRepository: 'Open GitHub repository', softwareUpdate: 'Software update', updateLead: 'Check for and install new Cyrene Compass releases.', checkUpdate: 'Check for updates', checkingUpdate: 'Checking', latestVersion: 'You are using the latest version', updateAvailable: 'New version available', newVersion: 'Available version', releaseNotes: 'Release notes', downloadInstall: 'Download and install', installingUpdate: 'Downloading update', downloadProgress: 'Download progress', updateFailed: 'Update failed', missingInstaller: 'The release does not include a Windows x64 installer', quit: 'Quit application', quit1: 'Quit Cyrene Compass?', quit2: 'Do you really not want to keep Cyrene Compass running?', quit3: 'Final confirmation: the floating ball and tray icon will close.', continueQuit: 'Continue quitting', stay: 'Stay', executed: 'Executed', startupUpdated: 'Startup settings updated', inspectFailed: 'Could not inspect dropped item', emptyAction: 'New item', newMenu: 'New submenu'
  }
}

export function translate(language, key) { return messages[language]?.[key] ?? messages.zh[key] ?? key }
